import { Trade } from '#/business/rpsModel';
import { ColDef } from '@ag-grid-community/core';
import { dateSortComparator, booleanFormatter, tenorSortComparator } from './utils';

export const getInitialTradeColumnsDefinitions = (): ColDef<Trade>[] => [
  {
    field: 'key',
    // hide: true,
    // lockVisible: true,
  },
  {
    field: 'status',
    headerName: 'Status',
    width: 110,
  },
  {
    type: 'abColDefDate',
    field: 'executionDate',
    headerName: 'Execution date',
    width: 140,
  },
  {
    type: 'abColDefDate',
    field: 'executionDate',
    headerName: 'Execution time',
    width: 140,

    sort: 'desc',
  },
  {
    field: 'book',
    headerName: 'Book',
    width: 100,
  },
  {
    field: 'instrumentDescription',
    headerName: 'Instrument description',
    width: 180,
  },
  {
    type: 'abColDefDate',
    field: 'maturityDate',
    headerName: 'Maturity',
  },
  {
    type: 'abColDefDate',
    field: 'deliveryDate',
    headerName: 'Delivery',
    width: 110,
  },
  {
    type: 'abColDefDate',
    field: 'settlementDate',
    headerName: 'Settlement date',
    width: 140,
  },
  {
    field: 'isinCode',
    headerName: 'Code ISIN',
    width: 140,
  },
  {
    field: 'quantity',
    headerName: 'Quantity',
    type: 'abColDefNumber',
    width: 130,
    aggFunc: 'sum',
  },
  {
    field: 'price',
    headerName: 'Price',
    type: 'abColDefNumber',
    width: 80,
  },
  {
    field: 'currency',
    headerName: 'Ccy',
    width: 80,
  },
  {
    field: 'trader',
    headerName: 'Trader',
    width: 100,
  },
  {
    field: 'counterparty',
    headerName: 'Counterparty',
    width: 180,
  },
  {
    field: 'tradeId',
    headerName: 'Trade id',
    width: 120,
    aggFunc: 'count',
  },
  {
    type: 'abColDefDate',
    field: 'initialExecutionDate',
    headerName: 'Initial Execution date',
    width: 140,
    // hide: true,
  },
  {
    type: 'abColDefDate',
    field: 'initialExecutionDate',
    headerName: 'Initial Execution time',
    comparator: dateSortComparator,
    width: 140,
    // hide: true,
  },
  {
    field: 'initialQuantity',
    headerName: 'Initial Quantity',
    type: 'abColDefNumber',
    width: 130,
    aggFunc: 'sum',
    // hide: true,
  },
  {
    field: 'initialPrice',
    headerName: 'Initial Price',
    type: 'abColDefNumber',
    width: 80,
    // hide: true,
  },
  {
    field: 'initialCounterparty',
    headerName: 'Initial Counterparty',
    width: 180,
    // hide: true,
  },
  {
    field: 'sourceSystem',
    headerName: 'Source system',
    width: 140,
    // hide: true,
  },
  {
    field: 'cdr',
    headerName: 'Cdr',
    width: 100,
    // hide: true,
  },
  {
    field: 'productType',
    headerName: 'Product',
    width: 90,
    // hide: true,
  },
  {
    field: 'typology',
    headerName: 'Typology',
    width: 90,
    // hide: true,
  },
  {
    field: 'venue',
    headerName: 'Venue',
    width: 90,
    // hide: true,
  },
  {
    field: 'venueOrderId',
    headerName: 'Venue Order Id',
    width: 90,
    // hide: true,
  },
  {
    field: 'nbTrades',
    headerName: 'Nb Trades',
    width: 90,
    // hide: true,
  },
  {
    field: 'internalOrderId',
    headerName: 'Internal Order Id',
    width: 90,
    // hide: true,
  },
  {
    field: 'blockTradeId',
    headerName: 'Block Id',
    width: 90,
    // hide: true,
  },
  {
    field: 'group',
    headerName: 'Group',
    width: 90,
    // hide: true,
  },
  {
    field: 'contractId',
    headerName: 'Contract id',
    width: 120,
    // hide: true,
  },
  {
    field: 'jsbId',
    headerName: 'Jsb id',
    // hide: true,
  },
  {
    type: 'abColDefDate',
    field: 'tradeDate',
    headerName: 'Trade date',
    // hide: true,
  },
  {
    type: 'abColDefDate',
    field: 'inputDate',
    headerName: 'Input date',
    width: 120,
    // hide: true,
  },
  {
    type: 'abColDefDate',
    field: 'modificationDate',
    headerName: 'Modification date',
    width: 160,
    // hide: true,
  },
  {
    type: 'abColDefDate',
    field: 'updatedAt',
    headerName: 'Updated at',
    comparator: dateSortComparator,
    width: 120,
    // hide: true,
  },
  {
    field: 'tradeVersion',
    headerName: 'Trade version',
    type: 'abColDefNumber',
    width: 140,
    // hide: true,
  },
  {
    field: 'direction',
    headerName: 'Direction',
    width: 130,
    // hide: true,
  },
  {
    field: 'notional',
    headerName: 'Notional',
    type: 'abColDefNumber',
    width: 130,
    aggFunc: 'sum',
    // hide: true,
  },
  {
    field: 'marketPrice',
    headerName: 'Market price',
    type: 'abColDefNumber',
    width: 140,
    // hide: true,
  },
  {
    field: 'priceType',
    headerName: 'Price type',
    // hide: true,
  },
  {
    field: 'yield',
    headerName: 'Yield',
    type: 'abColDefNumber',
    width: 140,
    // hide: true,
  },
  {
    field: 'marketYield',
    headerName: 'Market yield',
    type: 'abColDefNumber',
    width: 140,
    // hide: true,
  },
  {
    field: 'bpv',
    headerName: 'BPV',
    type: 'abColDefNumber',
    width: 100,
    // hide: true,
  },
  {
    field: 'pv01',
    headerName: 'Pv01',
    type: 'abColDefNumber',
    width: 90,
    // hide: true,
  },
  {
    field: 'marketValue',
    headerName: 'Market Value',
    type: 'abColDefNumber',
    width: 120,
    // hide: true,
  },
  {
    type: 'abColDefDate',
    field: 'issueDate',
    headerName: 'Issue date',
    comparator: dateSortComparator,
    // hide: true,
  },
  {
    field: 'tenor',
    headerName: 'Tenor',
    comparator: tenorSortComparator,
    width: 110,
    // hide: true,
  },
  {
    field: 'instrumentLabel',
    headerName: 'Instrument',
    width: 140,
    // hide: true,
  },
  {
    field: 'issuer',
    headerName: 'Issuer',
    width: 180,
    // hide: true,
  },
  {
    field: 'issueLongDescription',
    headerName: 'Issue long description',
    width: 180,
    // hide: true,
  },
  {
    field: 'couponRate',
    headerName: 'Coupon rate',
    type: 'abColDefNumber',
    width: 140,
    // hide: true,
  },
  {
    field: 'country',
    headerName: 'Country',
    // hide: true,
  },
  {
    field: 'isCancelled',
    headerName: 'Is cancelled',
    valueFormatter: booleanFormatter(false),
    width: 120,
    // hide: true,
  },
  {
    field: 'isSod',
    headerName: 'Is sod',
    valueFormatter: booleanFormatter(false),
    // hide: true,
  },
  {
    field: 'manualTrade',
    headerName: 'Is manual',
    valueFormatter: booleanFormatter(false),
    width: 120,
    // hide: true,
  },
  {
    field: 'isConfirmed',
    headerName: 'Is confirmed',
    valueFormatter: booleanFormatter(false),
    width: 120,
    // hide: true,
  },
  {
    field: 'isBlockTrade',
    headerName: 'Is Block Trade',
    valueFormatter: booleanFormatter(false),
    width: 120,
    // hide: true,
  },
  {
    field: 'exchangeTicker',
    headerName: 'Exchange ticker',
    width: 140,
    // hide: true,
  },
  {
    field: 'ticker',
    headerName: 'Ticker',
    width: 100,
    // hide: true,
  },
  {
    field: 'bloombergTicker',
    headerName: 'Bloomberg ticker',
    width: 160,
    // hide: true,
  },
  {
    field: 'market',
    headerName: 'Market ID',
    width: 120,
    // hide: true,
  },
  {
    field: 'futCode',
    headerName: 'Fut code',
    // hide: true,
  },
  {
    field: 'futureType',
    headerName: 'Future type',
    width: 140,
    // hide: true,
  },
  {
    field: 'contractMaturity',
    headerName: 'Contract maturity',
    width: 190,
    // hide: true,
  },
  {
    field: 'contractTicker',
    headerName: 'Contract ticker',
    width: 140,
    // hide: true,
  },
  {
    field: 'counterpartyRicosId',
    headerName: 'Cpty RICOS Id',
    width: 200,
    // hide: true,
  },
  {
    field: 'brokerRicosId',
    headerName: 'Broker RICOS Id',
    width: 200,
    // hide: true,
  },
  {
    field: 'broker',
    headerName: 'Broker',
    width: 110,
    // hide: true,
  },
  {
    field: 'rfqId',
    headerName: 'RFQ Id',
    width: 200,
    // hide: true,
  },
  {
    field: 'swapPayCurrency',
    headerName: 'P ccy',
    width: 100,
    // hide: true,
  },
  {
    field: 'swapPayAmount',
    headerName: 'P amount',
    type: 'abColDefNumber',
    width: 120,
    // hide: true,
  },
  {
    type: 'abColDefDate',
    field: 'swapPayStartDate',
    headerName: 'P start date',
    comparator: dateSortComparator,
    width: 150,
    // hide: true,
  },
  {
    type: 'abColDefDate',
    field: 'swapPayMaturityDate',
    headerName: 'P maturity date',
    comparator: dateSortComparator,
    width: 150,
    // hide: true,
  },
  {
    field: 'swapPayRateType',
    headerName: 'P fixed or float',
    width: 150,
    // hide: true,
  },
  {
    field: 'swapPayIndex',
    headerName: 'P index',
    width: 200,
    // hide: true,
  },
  {
    field: 'swapPayDayCount',
    headerName: 'P daycount',
    width: 120,
    // hide: true,
  },
  {
    field: 'swapPayFrequency',
    headerName: 'P frequency',
    width: 200,
    // hide: true,
  },
  {
    field: 'swapRecCurrency',
    headerName: 'R ccy',
    width: 100,
    // hide: true,
  },
  {
    field: 'swapRecAmount',
    headerName: 'R amount',
    type: 'abColDefNumber',
    width: 120,
    // hide: true,
  },
  {
    type: 'abColDefDate',
    field: 'swapRecStartDate',
    headerName: 'R start date',
    comparator: dateSortComparator,
    width: 150,
    // hide: true,
  },
  {
    type: 'abColDefDate',
    field: 'swapRecMaturityDate',
    headerName: 'R maturity date',
    comparator: dateSortComparator,
    width: 150,
    // hide: true,
  },
  {
    field: 'swapRecRateType',
    headerName: 'R fixed or float',
    width: 150,
    // hide: true,
  },
  {
    field: 'swapRecIndex',
    headerName: 'R index',
    width: 200,
    // hide: true,
  },
  {
    field: 'swapRecDayCount',
    headerName: 'R daycount',
    width: 120,
    // hide: true,
  },
  {
    field: 'swapRecFrequency',
    headerName: 'R frequency',
    width: 200,
    // hide: true,
  },
  {
    type: 'abColDefDate',
    field: 'inputDate',
    headerName: 'Input time',
    comparator: dateSortComparator,
    width: 120,
    // hide: true,
  },
  {
    type: 'abColDefDate',
    field: 'modificationDate',
    headerName: 'Modification time',
    comparator: dateSortComparator,
    width: 160,
    // hide: true,
  },
  {
    field: 'settlementAmount',
    headerName: 'Settlement Amount',
    type: 'abColDefNumber',
    width: 120,
    // hide: true,
  },
  {
    field: 'signedQuantity',
    headerName: 'Signed Quantity',
    type: 'abColDefNumber',
    width: 130,
    aggFunc: 'sum',
    // hide: true,
  },
  {
    field: 'signedNotional',
    headerName: 'Signed Notional',
    type: 'abColDefNumber',
    width: 130,
    aggFunc: 'sum',
    // hide: true,
  },
  {
    field: 'signedSodNotional',
    headerName: 'Sod Signed Notional',
    type: 'abColDefNumber',
    width: 130,
    aggFunc: 'sum',
    // hide: true,
  },
  {
    field: 'cashNew',
    headerName: 'Cash New',
    type: 'abColDefNumber',
    width: 130,
    aggFunc: 'sum',
    // hide: true,
  },
  {
    field: 'cashSod',
    headerName: 'Cash Sod',
    type: 'abColDefNumber',
    width: 130,
    aggFunc: 'sum',
    // hide: true,
  },
  {
    field: 'sodMarketValue',
    headerName: 'Market Value Sod',
    type: 'abColDefNumber',
    width: 130,
    aggFunc: 'sum',
    // hide: true,
  },
  {
    field: 'rate',
    headerName: 'Rate',
    type: 'abColDefNumber',
    width: 110,
    aggFunc: 'sum',
    // hide: true,
  },
];
